module.exports = {
	ADD_SUCCESS: 'ADD_SUCCESS',
	GET_SUCCESS: 'GET_SUCCESS',
	GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCESS',
	LIST_SUCCESS: 'LIST_SUCCESS',
	SET_LOADING: 'SET_LOADING',
	RESET_LOADING: 'RESET_LOADING',
	UPDATE_SUCCESS: 'UPDATE_SUCCESS',
	ARCHIVE_SUCCESS: 'ARCHIVE_SUCCESS',
	DELETE_SUCCESS: 'DELETE_SUCCESS'
};
